Read the data with pandas and find features and target variables

In [20]:
import pandas as pd
d=pd.read_csv("/train.csv")
d

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [21]:
y=d['price_range']
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [22]:
x=d.drop('price_range',axis=1)
x

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1
1997,1911,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0
1998,1512,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1
1999,510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1

Normalize the data with min-max scaling

In [23]:
df=x-x.min()/(x.max()-x.min())
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,841.665331,0.0,2.0,0.0,1.0,0.0,6.967742,0.488889,187.333333,1.857143,2.0,20.0,755.666222,2548.931587,8.642857,7.0,18.888889,0.0,0.0,1.0
1,1020.665331,1.0,0.3,1.0,0.0,1.0,52.967742,0.588889,135.333333,2.857143,6.0,905.0,1987.666222,2630.931587,16.642857,3.0,6.888889,1.0,1.0,0.0
2,562.665331,1.0,0.3,1.0,2.0,1.0,40.967742,0.788889,144.333333,4.857143,6.0,1263.0,1715.666222,2602.931587,10.642857,2.0,8.888889,1.0,1.0,0.0
3,614.665331,1.0,2.3,0.0,0.0,0.0,9.967742,0.688889,130.333333,5.857143,9.0,1216.0,1785.666222,2768.931587,15.642857,8.0,10.888889,1.0,0.0,0.0
4,1820.665331,1.0,1.0,0.0,13.0,1.0,43.967742,0.488889,140.333333,1.857143,14.0,1208.0,1211.666222,1410.931587,7.642857,2.0,14.888889,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,793.665331,1.0,0.3,1.0,0.0,1.0,1.967742,0.688889,105.333333,5.857143,14.0,1222.0,1889.666222,667.931587,12.642857,4.0,18.888889,1.0,1.0,0.0
1996,1964.665331,1.0,2.4,1.0,0.0,0.0,38.967742,0.088889,186.333333,3.857143,3.0,915.0,1964.666222,2031.931587,10.642857,10.0,15.888889,1.0,1.0,1.0
1997,1910.665331,0.0,0.7,1.0,1.0,1.0,35.967742,0.588889,107.333333,7.857143,3.0,868.0,1631.666222,3056.931587,8.642857,1.0,4.888889,1.0,1.0,0.0
1998,1511.665331,0.0,0.7,0.0,4.0,1.0,45.967742,-0.011111,144.333333,4.857143,5.0,336.0,669.666222,868.931587,17.642857,10.0,18.888889,1.0,1.0,1.0
1999,509.665331,1.0,1.8,1.0,5.0,1.0,44.967742,0.788889,167.333333,5.857143,16.0,483.0,753.666222,3918.931587,18.642857,4.0,1.888889,1.0,1.0,1.0

Split the data into train and test.

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df,y,test_size=0.2,random_state=40)
x_test,x_train,y_test,y_train

(      battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
 423     1680.665331   1.0          2.3       0.0   2.0     0.0   10.967742
 1495    1471.665331   0.0          2.8       0.0   4.0     1.0   19.967742
 1618     501.665331   0.0          0.6       0.0   7.0     0.0   51.967742
 1099    1696.665331   0.0          0.3       0.0   0.0     1.0   59.967742
 1307     830.665331   0.0          1.5       1.0   7.0     1.0   25.967742
 ...             ...   ...          ...       ...   ...     ...         ...
 739     1302.665331   0.0          0.8       1.0   0.0     1.0   14.967742
 1379     770.665331   0.0          2.7       0.0   2.0     0.0   61.967742
 837      786.665331   1.0          0.3       0.0  15.0     0.0   10.967742
 877     1443.665331   0.0          0.4       0.0   2.0     0.0   47.967742
 828     1964.665331   0.0          0.3       0.0   6.0     1.0    3.967742

          m_dep   mobile_wt   n_cores    pc  px_height     px_width  \
 423   0.288889  157.333333  1.857143  13.0      195.0  1204.666222
 1495  0.188889  168.333333  1.857143   6.0      443.0   891.666222
 1618  0.888889   81.333333  5.857143   8.0      281.0  1158.666222
 1099 -0.011111   89.333333  3.857143   0.0       88.0  1045.666222
 1307  0.588889  176.333333  4.857143  11.0      511.0   620.666222
 ...        ...         ...       ...   ...        ...          ...
 739  -0.011111  137.333333  2.857143  10.0      229.0  1603.666222
 1379  0.588889  105.333333  0.857143   8.0     1709.0  1780.666222
 837   0.488889   92.333333  0.857143  16.0      806.0  1422.666222
 877   0.388889   81.333333  4.857143  17.0     1092.0  1553.666222
 828   0.888889   83.333333  6.857143   9.0      977.0  1659.666222

               ram       sc_h  sc_w  talk_time  three_g  touch_screen  wifi
 423   1121.931587  11.642857   6.0  15.888889      0.0           1.0   1.0
 1495   796.931587   5.642857   1.0  10.888889      1.0           1.0   0.0
 1618  2665.931587   4.642857   4.0  19.888889      1.0           1.0   0.0
 1099   440.931587  14.642857   1.0  10.888889      1.0           1.0   0.0
 1307  1703.931587   5.642857   5.0  19.888889      1.0           1.0   1.0
 ...           ...        ...   ...        ...      ...           ...   ...
 739   2573.931587  11.642857   4.0  13.888889      1.0           1.0   1.0
 1379  1627.931587   8.642857   3.0   5.888889      0.0           1.0   0.0
 837   2933.931587   7.642857   6.0  13.888889      1.0           0.0   1.0
 877   2539.931587  16.642857   2.0  14.888889      1.0           1.0   1.0
 828   3534.931587  16.642857   0.0  15.888889      1.0           1.0   1.0

 [400 rows x 20 columns],
       battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
 1239    1239.665331   0.0          1.4       0.0   0.0     0.0   38.967742
 426     1189.665331   1.0          2.0       1.0   9.0     0.0   46.967742
 1249     503.665331   1.0          2.6       1.0   2.0     0.0   53.967742
 727     1589.665331   0.0          0.4       1.0   0.0     0.0    6.967742
 800     1438.665331   0.0          0.7       0.0  12.0     1.0   19.967742
 ...             ...   ...          ...       ...   ...     ...         ...
 1016     550.665331   1.0          2.6       0.0   0.0     1.0   53.967742
 165      516.665331   0.0          1.2       1.0   3.0     1.0   32.967742
 7       1953.665331   0.0          0.3       1.0   0.0     0.0   23.967742
 219     1550.665331   0.0          0.9       0.0   4.0     0.0   50.967742
 1350    1397.665331   0.0          1.4       1.0   8.0     1.0   25.967742

          m_dep   mobile_wt   n_cores    pc  px_height     px_width  \
 1239 -0.011111  145.333333  1.857143   9.0     1511.0  1755.666222
 426   0.188889  185.333333  5.857143  10.0     1417.0  1440.666222
 1249  0.288889  162.333333  1.857143  10.0     1207.0  1538.666222
 727   0.188889  121.333333  2.857143  17.0     1464.0  1594.666222
 800   0.688889  146.333333  0.857143  17.0      626.0   931.666222
 ...        ...         ...       ...   ...        ...          ...
 1016 -0.011111  171.333333  6.857143  15.0      169.0  1915.666222
 165   0.688889  182.333333  3.857143   8.0      660.0   973.666222
 7     0.688889  186.333333  3.857143   0.0      512.0  1148.666222
 219  -0.011111   87.333333  4.857143   6.0     1738.0  1994.666222
 1350  0.688889  149.333333  0.857143  12.0      755.0  1283.666222

               ram       sc_h  sc_w  talk_time  three_g  touch_screen  wifi
 1239  3259.931587  12.642857   1.0  16.888889      0.0           0.0   1.0
 426    623.931587   8.642857   3.0  18.888889      1.0           1.0   1.0
 1249  2377.931587  16.642857  11.0   1.888889      1.0           0.0   0.0
 727   1200.931587  11.642857   3.0  17.888889      1.0           1.0   1.0
 800   1789.931587  18.642857  12.0  14.888889      1.0           0.0   1.0
 ...           ...        ...   ...        ...      ...           ...   ...
 1016  1413.931587   5.642857   1.0  18.888889      1.0           0.0   1.0
 165   3703.931587  16.642857  16.0  10.888889      1.0           0.0   1.0
 7      699.931587  15.642857   3.0   4.888889      1.0           1.0   1.0
 219   3843.931587  10.642857   8.0   3.888889      0.0           1.0   0.0
 1350  3487.931587  13.642857   3.0  10.888889      1.0           1.0   0.0

 [1600 rows x 20 columns],
 423     0
 1495    0
 1618    2
 1099    0
 1307    0
        ..
 739     2
 1379    1
 837     2
 877     3
 828     3
 Name: price_range, Length: 400, dtype: int64,
 1239    3
 426     0
 1249    2
 727     1
 800     1
        ..
 1016    0
 165     3
 7       0
 219     3
 1350    3
 Name: price_range, Length: 1600, dtype: int64)

question-2: Read the data with pandas and describe the data

In [25]:
import pandas as pd
d1=pd.read_csv("/archive (2).zip")
d1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

Find data type and shape of each column

In [26]:
g=d1.dtypes
print(g)
print(d1.shape)

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object
(20640, 10)

Find the target and features

In [27]:
y=d1['housing_median_age']
y

0        41.0
1        21.0
2        52.0
3        52.0
4        52.0
         ...
20635    25.0
20636    18.0
20637    17.0
20638    18.0
20639    16.0
Name: housing_median_age, Length: 20640, dtype: float64

In [28]:
x=d1.drop('housing_median_age',axis=1)
x

,longitude,latitude,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

Find the null values (if yes fill the null values with ‘0’ or mean of that column)

In [29]:
x.isnull().sum()

longitude               0
latitude                0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Normalize all the features

In [30]:
df=y-y.min()/(y.max()-y.min())
df

0        40.980392
1        20.980392
2        51.980392
3        51.980392
4        51.980392
           ...
20635    24.980392
20636    17.980392
20637    16.980392
20638    17.980392
20639    15.980392
Name: housing_median_age, Length: 20640, dtype: float64

Split the data into train and test.

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=42)
x_train,x_test,y_train,y_test

(       longitude  latitude  total_rooms  total_bedrooms  population  \
 5967     -117.81     34.10       1935.0           399.0      1126.0
 17744    -121.76     37.29       2267.0           348.0      1150.0
 952      -121.94     37.71       6473.0          1027.0      2484.0
 9361     -122.53     37.96       4385.0           620.0      1549.0
 11024    -117.83     33.79       1454.0           236.0       724.0
 ...          ...       ...          ...             ...         ...
 11284    -117.96     33.78       1330.0           201.0       658.0
 11964    -117.43     34.02       3084.0           570.0      1753.0
 5390     -118.38     34.03       2101.0           569.0      1756.0
 860      -121.96     37.58       3575.0           597.0      1777.0
 15795    -122.42     37.77       4226.0          1315.0      2619.0

        households  median_income  median_house_value ocean_proximity
 5967        389.0         3.8929            144600.0          INLAND
 17744       327.0         7.1267            277900.0       <1H OCEAN
 952         970.0         5.0143            271100.0       <1H OCEAN
 9361        626.0         8.3935            470500.0        NEAR BAY
 11024       262.0         4.8542            218100.0       <1H OCEAN
 ...           ...            ...                 ...             ...
 11284       217.0         6.3700            229200.0       <1H OCEAN
 11964       449.0         3.0500             97800.0          INLAND
 5390        527.0         2.9344            222100.0       <1H OCEAN
 860         559.0         5.7192            283500.0       <1H OCEAN
 15795      1242.0         2.5755            325000.0        NEAR BAY

 [10320 rows x 9 columns],
        longitude  latitude  total_rooms  total_bedrooms  population  \
 20046    -119.01     36.06       1505.0             NaN      1392.0
 3024     -119.46     35.14       2943.0             NaN      1565.0
 15663    -122.44     37.80       3830.0             NaN      1310.0
 20484    -118.72     34.28       3051.0             NaN      1705.0
 9814     -121.93     36.62       2351.0             NaN      1063.0
 ...          ...       ...          ...             ...         ...
 10907    -117.85     33.75       2311.0           632.0      2936.0
 3231     -119.57     36.27       2673.0           452.0      1394.0
 18240    -122.08     37.40        766.0           203.0       448.0
 2484     -120.38     36.15       2279.0           448.0      1200.0
 7205     -118.19     34.02       1478.0           369.0      1735.0

        households  median_income  median_house_value ocean_proximity
 20046       359.0         1.6812             47700.0          INLAND
 3024        584.0         2.5313             45800.0          INLAND
 15663       963.0         3.4801            500001.0        NEAR BAY
 20484       495.0         5.7376            218600.0       <1H OCEAN
 9814        428.0         3.7250            278000.0      NEAR OCEAN
 ...           ...            ...                 ...             ...
 10907       609.0         2.5651            171400.0       <1H OCEAN
 3231        449.0         2.6250             97400.0          INLAND
 18240       196.0         2.5208            316700.0        NEAR BAY
 2484        420.0         2.7461             70000.0          INLAND
 7205        348.0         1.8875            136700.0       <1H OCEAN

 [10320 rows x 9 columns],
 5967     19.0
 17744    15.0
 952      15.0
 9361     36.0
 11024    29.0
          ...
 11284    35.0
 11964    33.0
 5390     36.0
 860      15.0
 15795    52.0
 Name: housing_median_age, Length: 10320, dtype: float64,
 20046    25.0
 3024     30.0
 15663    52.0
 20484    17.0
 9814     34.0
          ...
 10907    27.0
 3231     20.0
 18240    52.0
 2484     17.0
 7205     34.0
 Name: housing_median_age, Length: 10320, dtype: float64)